FROM ubuntu:20.04

ARG GIT_VERSION
ARG DOWNLOAD_URL

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev \
    gettext unzip wget tar zlib1g-dev && \
    apt-get clean

WORKDIR /build

RUN wget "$DOWNLOAD_URL" && \
    tar -xzf git-${GIT_VERSION}.tar.gz && \
    cd git-${GIT_VERSION} && \
    make prefix=/opt/git install

RUN tar -czf /git-${GIT_VERSION}-ubuntu.tar.gz -C /opt git
